pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'docker build -t capstone-app week1-foundations/capstone'
            }
        }
        stage ('Security scan') {
            steps {
                sh 'docker run --rm aquasec/trivy image --exit-code 0 --severity HIGH,CRITICAL capstone-app'
            }
        }
        stage ('Deploy') {
            steps {
                sh 'docker rm -f capstone-app-container || true'
                sh 'docker run -d --name capstone-app-container -p 8000:8000 capstone-app'
                sh 'sleep 3'
            }
        }
        stage ('test') {
            steps {
                sh 'chmod +x week1-foundations/capstone/healthcheck.sh'
                sh './week1-foundations/capstone/healthcheck.sh'
            }
        }
    }
    post {
        always {
            sh 'docker rm -f capstone-app-container || true'
        }
    }
}