name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Build step
       run: echo "Building the application .."

     - name: Test step
       run: echo "Running tests..."

     - name: Deploying step
       run: echo "Deploying ..."

